spec-version: 0.36.0
name: sensei
version: 0.9.0
synopsis: Automatically run Hspec tests on file modifications
author: Simon Hengel <sol@typeful.net>
maintainer: Simon Hengel <sol@typeful.net>
license: MIT
github: hspec/sensei
category: Development

language: GHC2021
default-extensions:
  - DuplicateRecordFields
  - LambdaCase
  - NoFieldSelectors
  - OverloadedRecordDot
  - OverloadedStrings
  - RecordWildCards
  - ViewPatterns
  - BlockArguments
  - DerivingVia

dependencies:
  - base >= 4.11 && < 5
  - pretty
  - process
  - fsnotify == 0.4.*
  - time
  - wai
  - warp
  - http-types
  - http-media
  - stm
  - text
  - network
  - ansi-terminal
  - directory
  - http-client >= 0.5.0
  - http-conduit
  - bytestring >= 0.11
  - filepath
  - unix
  - async
  - containers
  - transformers
  - mtl >= 2.3.1
  - aeson
  - yaml
  - casing
  - temporary

ghc-options: -Wall -threaded

source-dirs:
  - src

library:
  exposed-modules: Sensei.API

executables:
  sensei:
    source-dirs: driver
    main: sensei.hs

  sensei-web:
    source-dirs: driver
    main: sensei-web.hs

  seito:
    source-dirs: driver
    main: seito.hs

tests:
  spec:
    main: Spec.hs
    source-dirs:
      - test
    dependencies:
      - hspec >= 2.9.0
      - hspec-contrib >= 0.5.2
      - QuickCheck
      - hspec-wai
      - wai-extra
      - mockery
      - vcr
    cpp-options: -DTEST
    build-tools: hspec-discover
