dependencies:
  - base == 4.*
  - process
  - fsnotify
  - time
  - wai
  - warp
  - http-types
  - system-filepath
  - stm

ghc-options: -Wall

library:
  source-dirs: 
    - src
    - doctest/ghci-wrapper/src/

executables:
  autospec:
    main: driver/Main.hs
    dependencies:
      - autospec

  autospec-web:
    main: driver/Web.hs
    dependencies:
      - autospec

tests:
  spec:
    main: Spec.hs
    source-dirs:
      - test
      - doctest/ghci-wrapper/src/
    dependencies:
      - autospec
      - hspec == 2.*
      - silently
