spec-version: 0.36.0
name: sensei
version: 0.9.0
synopsis: Automatically run Hspec tests on file modifications
author: Simon Hengel <sol@typeful.net>
maintainer: Simon Hengel <sol@typeful.net>
license: MIT
github: hspec/sensei
category: Development

language: GHC2021
default-extensions:
  - NoImplicitPrelude
  - DuplicateRecordFields
  - LambdaCase
  - NoFieldSelectors
  - OverloadedRecordDot
  - OverloadedStrings
  - RecordWildCards
  - ViewPatterns
  - BlockArguments
  - PackageImports
  - DerivingVia

dependencies:
  - ghc-diagnostics

  - base >= 4.18 && < 5
  - process
  - fsnotify == 0.4.*
  - time
  - wai
  - warp
  - http-types
  - http-media
  - stm
  - text >= 2.1
  - network
  - ansi-terminal
  - directory
  - http-client >= 0.5.0
  - http-conduit
  - bytestring >= 0.11
  - filepath
  - unix
  - async
  - containers
  - transformers
  - mtl >= 2.3.1
  - aeson
  - yaml
  - casing
  - temporary
  - clock
  - double-conversion
  - ghc
  - ghc-hie >= 0.0.4
  - Cabal-syntax
  - strip-ansi

ghc-options: -Wall -threaded

source-dirs:
  - src

library:
  exposed-modules: Sensei.API
  ghc-options: -Wunused-packages

executables:
  sensei:
    source-dirs: driver
    main: sensei.hs

  seito:
    source-dirs: driver
    main: seito.hs

tests:
  spec:
    main: Spec.hs
    source-dirs:
      - test
    dependencies:
      - hspec >= 2.9.0
      - hspec-contrib >= 0.5.2
      - HUnit
      - QuickCheck
      - hspec-wai
      - mockery
      - vcr
      - template-haskell
    cpp-options: -DTEST
    ghc-options: -Wunused-packages
    build-tools: hspec-discover
