name: publish

permissions:
  contents: write

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - run: cabal check --ignore=missing-upper-bounds

      - uses: sol/haskell-autotag@v1
        id: autotag
        with:
          prefix: null

      - run: cabal sdist

      - uses: haskell-actions/hackage-publish@v1.1
        with:
          hackageToken: ${{ secrets.HACKAGE_AUTH_TOKEN }}
          publish: true
        if: steps.autotag.outputs.created

      - name: publish binaries
        run: |
          cabal update
          cabal build --disable-tests --disable-benchmarks --disable-documentation --enable-optimization
          assets=()
          for binary in sensei seito; do
            asset="${binary}_linux.gz"
            cat "$(cabal list-bin $binary)" | gzip > "$asset"
            assets+=("$asset")
          done
          gh release create ${{ steps.autotag.outputs.name }} --title ${{ steps.autotag.outputs.name }} --verify-tag "${assets[@]}"
        env:
          GH_TOKEN: ${{ github.token }}
        if: steps.autotag.outputs.created
