name: publish

permissions:
  contents: write
  actions: read

concurrency:
  group: publish
  cancel-in-progress: false

on:
  workflow_run:
    workflows:
      - build
    types:
      - completed
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    if: github.event.workflow_run.conclusion == 'success'
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.workflow_run.head_sha }}

      - uses: sol/haskell-autotag@v1
        id: autotag
        with:
          prefix: null

      - run: cabal sdist

      - uses: haskell-actions/hackage-publish@v1.1
        with:
          hackageToken: ${{ secrets.HACKAGE_AUTH_TOKEN }}
          publish: true
        if: steps.autotag.outputs.created

      - uses: actions/download-artifact@v4
        with:
          merge-multiple: true
          github-token: ${{ github.token }}
          run-id: ${{ github.event.workflow_run.id }}

      - name: Publish binaries
        run: gh release create --verify-tag ${{ steps.autotag.outputs.name }} *.gz
        env:
          GH_TOKEN: ${{ github.token }}
        if: steps.autotag.outputs.created

      - name: Publish preview binaries
        run: |
          git tag preview -f
          git push origin preview -f
          gh release upload preview --clobber *.gz
        env:
          GH_TOKEN: ${{ github.token }}
        if: "!steps.autotag.outputs.created"
